apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmdb-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: cmdb-ui
    tier: frontend
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: cmdb-ui
  template:
    metadata:
      labels:
        app: cmdb-ui
        tier: frontend
    spec:
      containers:
        - name: cmdb-ui
          image: {{ .Values.ui.image }}:{{ .Values.ui.tag | default "latest" }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5